spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_PATH}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    show-sql: true

kakao:
  api:
    key: ${KAKAO_API_KEY}

  base:
    x: ${BASE_PLACE_X}
    y: ${BASE_PLACE_Y}