spring:
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_PATH}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    show-sql: true

kakao:
  api:
    key: ${KAKAO_API_KEY}

  base:
    x: 127.1069920
    y: 37.4003784